-- liquibase formatted sql
-- changeset ttg:202607170001__0.0.1__DKP-0020__add_task_management_tables logicalFilePath:DevKnowledgePlatform
-- comment: Task/project management — projects and tasks, with optional content-item linkage

CREATE SEQUENCE IF NOT EXISTS product.PROJECT_SEQ
    START WITH 1 INCREMENT BY 50 NO MAXVALUE NO CYCLE;

CREATE TABLE IF NOT EXISTS product.PROJECT (
    PROJECT_ID              INTEGER                         NOT NULL,
    NAME                    VARCHAR(255)                    NOT NULL,
    DESCRIPTION             TEXT,
    OWNER_ID                INTEGER                         NOT NULL,
    STATUS                  VARCHAR(50)                     NOT NULL,
    USR_CREATION            VARCHAR(128)                    NOT NULL,
    DTE_CREATION            TIMESTAMP WITH TIME ZONE        NOT NULL,
    USR_LAST_MODIFICATION   VARCHAR(128)                    NOT NULL,
    DTE_LAST_MODIFICATION   TIMESTAMP WITH TIME ZONE        NOT NULL,
    VERSION                 INTEGER                         NOT NULL,

    CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID),
    CONSTRAINT FK_PROJECT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES product.USER (USER_ID),
    CONSTRAINT CKC_PROJECT_STATUS CHECK (STATUS IN ('ACTIVE','ARCHIVED'))
);

ALTER SEQUENCE product.PROJECT_SEQ OWNED BY product.PROJECT.PROJECT_ID;

CREATE INDEX IF NOT EXISTS IDX_PROJECT_OWNER ON product.PROJECT (OWNER_ID);

CREATE SEQUENCE IF NOT EXISTS product.TASK_SEQ
    START WITH 1 INCREMENT BY 50 NO MAXVALUE NO CYCLE;

CREATE TABLE IF NOT EXISTS product.TASK (
    TASK_ID                 INTEGER                         NOT NULL,
    PROJECT_ID              INTEGER,
    OWNER_ID                INTEGER                         NOT NULL,
    TITLE                   VARCHAR(255)                    NOT NULL,
    DESCRIPTION             TEXT,
    STATUS                  VARCHAR(50)                     NOT NULL,
    PRIORITY                VARCHAR(50)                     NOT NULL,
    DUE_DATE                TIMESTAMP WITH TIME ZONE,
    CONTENT_ITEM_ID         INTEGER,
    USR_CREATION            VARCHAR(128)                    NOT NULL,
    DTE_CREATION            TIMESTAMP WITH TIME ZONE        NOT NULL,
    USR_LAST_MODIFICATION   VARCHAR(128)                    NOT NULL,
    DTE_LAST_MODIFICATION   TIMESTAMP WITH TIME ZONE        NOT NULL,
    VERSION                 INTEGER                         NOT NULL,

    CONSTRAINT PK_TASK PRIMARY KEY (TASK_ID),
    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES product.PROJECT (PROJECT_ID),
    CONSTRAINT FK_TASK_OWNER FOREIGN KEY (OWNER_ID) REFERENCES product.USER (USER_ID),
    CONSTRAINT FK_TASK_CONTENT_ITEM FOREIGN KEY (CONTENT_ITEM_ID) REFERENCES product.CONTENT_ITEM (CONTENT_ITEM_ID),
    CONSTRAINT CKC_TASK_STATUS CHECK (STATUS IN ('TODO','IN_PROGRESS','DONE')),
    CONSTRAINT CKC_TASK_PRIORITY CHECK (PRIORITY IN ('LOW','MEDIUM','HIGH','URGENT'))
);

ALTER SEQUENCE product.TASK_SEQ OWNED BY product.TASK.TASK_ID;

CREATE INDEX IF NOT EXISTS IDX_TASK_PROJECT ON product.TASK (PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_TASK_OWNER ON product.TASK (OWNER_ID);
CREATE INDEX IF NOT EXISTS IDX_TASK_STATUS ON product.TASK (STATUS);
CREATE INDEX IF NOT EXISTS IDX_TASK_CONTENT_ITEM ON product.TASK (CONTENT_ITEM_ID);
