-- liquibase formatted sql
-- changeset ttg:202608050001__0.0.1__DKP-0024__create_keycloak_schema logicalFilePath:DevKnowledgePlatform
-- comment: Create the `keycloak` schema, same convention as DKP-0001 (product) and DKP-0023 (ecommerce)
--
-- DKP-0024: Keycloak (docker-compose's own `keycloak` service) shares this project's single
-- Postgres instance under its own schema, rather than a second database — same "one instance,
-- one schema per component" convention already used for `product`/`ecommerce`. Unlike those two,
-- Keycloak's own internal Liquibase migration does not create its schema itself; it assumes the
-- schema already exists and fails otherwise. This changeset is the one mechanism this project
-- already has for "create a schema before anything else needs it," so it owns Keycloak's schema
-- bootstrap too, even though nothing else in this changeset tree is a `gateway` concern — the
-- alternative (a bespoke one-shot docker-compose service running a bare CREATE SCHEMA) was tried
-- and reverted in favor of reusing this existing, already-idempotent mechanism.
--
-- Ordering note: `docker-compose -f dev-knowledge-platform-docker-compose.yml up -d` starts the
-- keycloak container before this migration has necessarily run, since Liquibase is a separate,
-- manual step in this project's workflow. Keycloak will fail to boot until this changeset has run
-- at least once; its `restart: on-failure` policy means it recovers automatically on its next
-- restart attempt once the schema exists, no manual restart needed.

CREATE SCHEMA IF NOT EXISTS keycloak;
